services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=badminton_club.settings.production
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
    ports:
      - "8000:8000"
    volumes:
      - .:/app
